### ISSUE TITLE
Installation improvements

### ISSUE THREAD

**Issue by apolkosnik** [JPCERTCC/aa-tools#3]
Hello,

I'd like to be able to install pyimpfuzzy via pip.
Obvious option would be to put the package on pypi.python.org or move the folder one level down so one can use perhaps:
```
pip install -e git+https://github.com/JPCERTCC/aa-tools.git#egg=pyimpfuzzy
```

Thanks in advance

**Comment by shu-tom** [comment]
Thank you for your request.
I uploaded to PyPI. Now you can use pip to install.
Please try it.

**Comment by apolkosnik** [comment]
Thanks, it works beautifully!
