### ISSUE TITLE
pip2.7 install fails...

### ISSUE THREAD

**Issue by crhea55906** [JPCERTCC/aa-tools#6]
Your tool is referenced in CRITs services, but cannot be installed via PIP:

pip2.7 install git+https://github.com/JPCERTCC/aa-tools.git

Collecting git+https://github.com/JPCERTCC/aa-tools.git
  Cloning https://github.com/JPCERTCC/aa-tools.git to ./pip-R87bsF-build
Unpacking objects: 100% (78/78), done.
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-R87bsF-build/setup.py'

**Comment by shu-tom** [comment]
This tool doesn't support pip install from GitHub.
impfuzzy is uploaded to the PyPI server. Now you can use "pip install impfuzzy".
Please try it.

**Comment by shu-tom** [comment]
This issue was pull requested to CRITs services.
https://github.com/crits/crits_services/pull/290

**Comment by crhea55906** [comment]
"pip2.7 install impfuzzy" fails... 

pip2.7 search impfuzzy only returns pyimpfuzzy (Python modules for impfuzzy).

(I'm no Python packaging expert, so if I'm missing something, please educate me...)
Thanks!

**Comment by shu-tom** [comment]
it's my fault.
Please try "pip install pyimpfuzzy".

**Comment by crhea55906** [comment]
Yup, that works... Wasn't clear to me that pyimpfuzzy was more than the Python API into impfuzzy.
If it *is* impfuzzy, we're OK now.  Thanks!
