### ISSUE TITLE
Sample impfuzzy values for testing

### ISSUE THREAD

**Issue by trixpan** [JPCERTCC/aa-tools#7]
Hi,

I am trying to port this into Java, would you have a set of "official" outputs I can use to validate the port?

**Comment by shu-tom** [comment]
This is a sample data table.
https://github.com/JPCERTCC/aa-tools/blob/master/impfuzzy/impfuzzy_for_Neo4j/test/Emdivi.csv

**Comment by trixpan** [comment]
@shu-tom - Wouldn't matching against those sums require me to have access to the malware samples?

I am more looking after data I can use to validate this https://github.com/fluenda/jImpfuzzy is compatible with your implementation. :-)

**Comment by shu-tom** [comment]
Great work!
I don't have datasets to use for testing.
